<template>
  <section class="page-card"><div class="page-heading"><div><p class="eyebrow">ACCESS CONTROL</p><h2>菜单管理</h2><p>统一维护导航、权限标识与操作点。</p></div><el-button v-if="canWrite" type="primary" @click="open()">新增菜单</el-button></div>
    <el-table :data="treeRows" v-loading="loading" row-key="id" default-expand-all :tree-props="{children:'children'}"><el-table-column prop="name" label="名称" min-width="190"/><el-table-column prop="type" label="类型" width="110"><template #default="{row}"><el-tag effect="plain">{{typeLabel[row.type]||row.type}}</el-tag></template></el-table-column><el-table-column prop="path" label="路由" min-width="190"/><el-table-column prop="permission" label="权限标识" min-width="210"/><el-table-column prop="sortOrder" label="排序" width="80"/><el-table-column label="可见" width="80"><template #default="{row}">{{row.visible?'是':'否'}}</template></el-table-column><el-table-column v-if="canWrite" label="操作" width="150"><template #default="{row}"><el-button link type="primary" @click="open(row)">编辑</el-button><el-button link type="danger" @click="remove(row)">删除</el-button></template></el-table-column></el-table>
  </section>
  <el-dialog v-model="visible" :title="form.id?'编辑菜单':'新增菜单'" width="620px"><el-form label-position="top"><el-row :gutter="16"><el-col :span="12"><el-form-item label="名称" required><el-input v-model="form.name"/></el-form-item></el-col><el-col :span="12"><el-form-item label="类型"><el-select v-model="form.type" style="width:100%"><el-option label="目录" value="DIRECTORY"/><el-option label="菜单" value="MENU"/><el-option label="按钮/权限点" value="BUTTON"/></el-select></el-form-item></el-col></el-row><el-form-item label="上级菜单"><el-select v-model="form.parentId" clearable style="width:100%"><el-option v-for="item in parentOptions" :key="item.id" :label="item.name" :value="item.id"/></el-select></el-form-item><el-row :gutter="16"><el-col :span="12"><el-form-item label="前端路由"><el-input v-model="form.path" placeholder="/system/example"/></el-form-item></el-col><el-col :span="12"><el-form-item label="图标"><el-input v-model="form.icon" placeholder="Element Plus 图标名"/></el-form-item></el-col></el-row><el-form-item label="权限标识"><el-input v-model="form.permission" placeholder="domain:resource:action"/></el-form-item><el-row :gutter="16"><el-col :span="8"><el-form-item label="排序"><el-input-number v-model="form.sortOrder" :min="0"/></el-form-item></el-col><el-col :span="8"><el-form-item label="导航可见"><el-switch v-model="form.visibleFlag"/></el-form-item></el-col><el-col :span="8"><el-form-item label="启用"><el-switch v-model="form.enabled"/></el-form-item></el-col></el-row></el-form><template #footer><el-button @click="visible=false">取消</el-button><el-button type="primary" :loading="saving" @click="save">保存</el-button></template></el-dialog>
</template>
<script setup>
import { computed,onMounted,reactive,ref } from 'vue'
import { ElMessage,ElMessageBox } from 'element-plus'
import { menuApi } from '../api'
import { hasPermission } from '../stores/auth'
const rows=ref([]),loading=ref(false),visible=ref(false),saving=ref(false)
const form=reactive({id:null,parentId:null,name:'',path:'',icon:'',permission:'',type:'MENU',sortOrder:0,visibleFlag:true,enabled:true})
const typeLabel={DIRECTORY:'目录',MENU:'菜单',BUTTON:'权限点'}
const canWrite=computed(()=>hasPermission('system:menu:write'))
const parentOptions=computed(()=>rows.value.filter(i=>i.id!==form.id&&i.type!=='BUTTON'))
const treeRows=computed(()=>{const map=new Map(rows.value.map(i=>[i.id,{...i,children:[]}])) ,roots=[];for(const item of map.values()){if(item.parentId&&map.has(item.parentId))map.get(item.parentId).children.push(item);else roots.push(item)}return roots})
const load=async()=>{loading.value=true;try{rows.value=await menuApi.list()}catch(e){ElMessage.error(e.message)}finally{loading.value=false}}
const open=row=>{Object.assign(form,row?{...row,visibleFlag:row.visible,enabled:row.status==='ENABLED'}:{id:null,parentId:null,name:'',path:'',icon:'',permission:'',type:'MENU',sortOrder:0,visibleFlag:true,enabled:true});visible.value=true}
const save=async()=>{if(!form.name.trim())return ElMessage.warning('请输入菜单名称');saving.value=true;try{const p={parentId:form.parentId,name:form.name,path:form.path,icon:form.icon,permission:form.permission,type:form.type,sortOrder:form.sortOrder,visible:form.visibleFlag,status:form.enabled?'ENABLED':'DISABLED'};form.id?await menuApi.update(form.id,p):await menuApi.create(p);visible.value=false;ElMessage.success('保存成功');await load()}catch(e){ElMessage.error(e.message)}finally{saving.value=false}}
const remove=async row=>{try{await ElMessageBox.confirm(`确认删除“${row.name}”？`,'删除确认',{type:'warning'});await menuApi.remove(row.id);ElMessage.success('已删除');await load()}catch(e){if(e!=='cancel')ElMessage.error(e.message)}}
onMounted(load)
</script>
