<template>
  <section class="page-card"><div class="page-heading"><div><p class="eyebrow">IDENTITY</p><h2>用户管理</h2><p>维护账号、组织岗位与职责角色。</p></div><el-button v-if="canWrite" type="primary" @click="open()">新增用户</el-button></div>
    <el-table :data="rows" v-loading="loading"><el-table-column prop="username" label="账号" min-width="130"/><el-table-column prop="displayName" label="姓名" min-width="120"/><el-table-column label="公司 / 岗位" min-width="200"><template #default="{row}">{{companyName(row.companyId)}}<small class="table-secondary">{{positionName(row.positionId)}}</small></template></el-table-column><el-table-column label="角色" min-width="180"><template #default="{row}"><el-tag v-for="name in row.roleNames" :key="name" effect="plain" class="role-tag">{{name}}</el-tag></template></el-table-column><el-table-column label="安全状态" min-width="150"><template #default="{row}"><el-tag v-if="row.lockedUntil" type="danger">已锁定</el-tag><el-tag v-else-if="row.mustChangePassword" type="warning">待改密</el-tag><el-tag v-else :type="row.status==='ENABLED'?'success':'info'">{{row.status==='ENABLED'?'正常':'停用'}}</el-tag></template></el-table-column><el-table-column prop="lastLoginAt" label="最近登录" min-width="170"/><el-table-column v-if="canWrite" label="操作" width="210" fixed="right"><template #default="{row}"><el-button link type="primary" @click="open(row)">编辑</el-button><el-button v-if="row.lockedUntil||row.failedLoginAttempts" link type="warning" @click="unlock(row)">解锁</el-button><el-button link type="danger" @click="remove(row)">删除</el-button></template></el-table-column></el-table>
  </section>
  <el-dialog v-model="visible" :title="form.id?'编辑用户':'新增用户'" width="680px"><el-form label-position="top"><el-row :gutter="16"><el-col :span="12"><el-form-item label="登录账号" required><el-input v-model="form.username"/></el-form-item></el-col><el-col :span="12"><el-form-item label="姓名" required><el-input v-model="form.displayName"/></el-form-item></el-col></el-row><el-row :gutter="16"><el-col :span="12"><el-form-item :label="form.id?'重置密码（留空不修改）':'初始密码'" :required="!form.id"><el-input v-model="form.password" type="password" show-password/></el-form-item></el-col><el-col :span="12"><el-form-item label="手机号"><el-input v-model="form.phone"/></el-form-item></el-col></el-row><el-form-item label="邮箱"><el-input v-model="form.email"/></el-form-item><el-row :gutter="16"><el-col :span="12"><el-form-item label="公司"><el-select v-model="form.companyId" clearable style="width:100%" @change="form.positionId=null"><el-option v-for="item in companies" :key="item.id" :label="item.name" :value="item.id"/></el-select></el-form-item></el-col><el-col :span="12"><el-form-item label="岗位"><el-select v-model="form.positionId" clearable style="width:100%"><el-option v-for="item in filteredPositions" :key="item.id" :label="item.name" :value="item.id"/></el-select></el-form-item></el-col></el-row><el-form-item label="角色"><el-select v-model="form.roleIds" multiple style="width:100%"><el-option v-for="item in roles" :key="item.id" :label="item.name" :value="item.id"/></el-select></el-form-item><el-row :gutter="16"><el-col :span="12"><el-form-item label="账号启用"><el-switch v-model="form.enabled"/></el-form-item></el-col><el-col :span="12"><el-form-item label="下次登录强制改密"><el-switch v-model="form.mustChangePassword"/></el-form-item></el-col></el-row><p class="form-help">密码需 12-64 位，并包含大写、小写、数字和特殊字符。</p></el-form><template #footer><el-button @click="visible=false">取消</el-button><el-button type="primary" :loading="saving" @click="save">保存</el-button></template></el-dialog>
</template>
<script setup>
import { computed,onMounted,reactive,ref } from 'vue'
import { ElMessage,ElMessageBox } from 'element-plus'
import { companyApi,positionApi,roleApi,userApi } from '../api'
import { hasPermission } from '../stores/auth'
const rows=ref([]),companies=ref([]),positions=ref([]),roles=ref([]),loading=ref(false),visible=ref(false),saving=ref(false)
const form=reactive({id:null,username:'',password:'',displayName:'',email:'',phone:'',companyId:null,positionId:null,roleIds:[],enabled:true,mustChangePassword:true})
const canWrite=computed(()=>hasPermission('system:user:write'))
const filteredPositions=computed(()=>positions.value.filter(i=>i.companyId===form.companyId))
const companyName=id=>companies.value.find(i=>i.id===id)?.name||'—'
const positionName=id=>positions.value.find(i=>i.id===id)?.name||'未分配岗位'
const load=async()=>{loading.value=true;try{[rows.value,companies.value,positions.value,roles.value]=await Promise.all([userApi.list(),companyApi.list(),positionApi.list(),roleApi.list()])}catch(e){ElMessage.error(e.message)}finally{loading.value=false}}
const open=row=>{Object.assign(form,row?{...row,password:'',enabled:row.status==='ENABLED',roleIds:[...row.roleIds]}:{id:null,username:'',password:'',displayName:'',email:'',phone:'',companyId:null,positionId:null,roleIds:[],enabled:true,mustChangePassword:true});visible.value=true}
const save=async()=>{if(!form.username.trim()||!form.displayName.trim()||(!form.id&&!form.password))return ElMessage.warning('请完整填写必填项');saving.value=true;try{const p={username:form.username,password:form.password,displayName:form.displayName,email:form.email,phone:form.phone,companyId:form.companyId,positionId:form.positionId,roleIds:form.roleIds,status:form.enabled?'ENABLED':'DISABLED',mustChangePassword:form.mustChangePassword};form.id?await userApi.update(form.id,p):await userApi.create(p);visible.value=false;ElMessage.success('保存成功');await load()}catch(e){ElMessage.error(e.message)}finally{saving.value=false}}
const unlock=async row=>{try{await userApi.unlock(row.id);ElMessage.success('账号已解锁');await load()}catch(e){ElMessage.error(e.message)}}
const remove=async row=>{try{await ElMessageBox.confirm(`确认删除账号“${row.username}”？`,'删除确认',{type:'warning'});await userApi.remove(row.id);ElMessage.success('已删除');await load()}catch(e){if(e!=='cancel')ElMessage.error(e.message)}}
onMounted(load)
</script>
